"""Stage 4 offline fallback: fill a paper skeleton from the Stage 3 results.

No LLM and no key. The prose is a fixed template; every number is read from
results/results.json, so the report can never disagree with the analysis.
It is a pseudo-paper: the shape of a research report, written by a script.

Run:  python 04_paper/make_paper.py [--results results] [--out paper/report.md]
"""
import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIGURE = "fig_pred_vs_obs.png"


def interval(pair, fmt=".3f"):
    return f"[{pair[0]:{fmt}}, {pair[1]:{fmt}}]"


def yes_no(flag, yes="contains", no="does not contain"):
    return yes if flag else no


def verdict(flag):
    return "Supported" if flag else "Not supported"


def build(r):
    hyp = {h["name"]: h for h in r["hypotheses"]}
    d, ex, mt, rv = r["data"], r["exponents"], r["mass_tests"], r["reveal"]
    rows_iv, groups_iv = ex["intervals_95"]["rows"], ex["intervals_95"]["groups"]
    g_rows, g_groups = rv["g_intervals_95"]["rows"], rv["g_intervals_95"]["groups"]
    g_acc = rv["g_accepted"]
    in_rows = g_rows[0] <= g_acc <= g_rows[1]
    in_groups = g_groups[0] <= g_acc <= g_groups[1]
    best = hyp[r["best_on_held_out"]]
    names = rv["groups"]
    train_names = ", ".join(names[g] for g in d["train_groups"])
    test_names = ", ".join(names[g] for g in d["test_groups"])

    table = [
        "| Hypothesis | Formula | Historical claim | Free parameters | Train error (dex) | Held-out error (dex) | BIC |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    claims = {
        "H1": "none (naive baseline)",
        "H2": "Kepler 1619, if p = 3/2",
        "H3": "none (free power law)",
        "H4": "Newton 1687",
    }
    for h in r["hypotheses"]:
        table.append(
            f"| {h['name']} | `{h['formula']}` | {claims[h['name']]} | {h['free_parameters']} "
            f"| {h['train_log_error']:.3f} | {h['test_log_error']:.3f} | {h['bic']:.1f} |"
        )

    evolved = r.get("openevolve_best")
    evolved_text = (
        f" The program evolved by OpenEvolve in Stage 2 reached a held-out error of "
        f"{evolved['test_log_error']:.3f} dex."
        if evolved and "test_log_error" in evolved
        else ""
    )

    return f"""# A power law in two variables, found blind, is Kepler's third law with Newton's mass term

*Pseudo-paper generated by `04_paper/make_paper.py` from `results/results.json`.
Template prose, computed numbers. Not peer reviewed.*

## Abstract

We were given {d['n_rows']} noisy measurements of three unnamed quantities in
arbitrary units, in {len(d['train_groups']) + len(d['test_groups'])} groups. Four
hypotheses were fitted on {len(d['train_groups'])} groups and judged on the other
{len(d['test_groups'])}. The best one on held-out groups was {best['name']},
`{best['formula']}`, with an error of {best['test_log_error']:.3f} dex. With free
exponents the fit gives p = {ex['p']:.3f} and q = {ex['q']:.3f}. After the
analysis the data were revealed to be orbits: the law is Kepler's third law
with Newton's dependence on the central mass, and it implies
G = {rv['g_estimate']:.3e} m³ kg⁻¹ s⁻² ({100 * rv['g_relative_error']:+.1f}% from the accepted value).

## 1. Introduction

Three early sources make claims that these data can test (full citations and
quotations in `literature/README.md`).

Galileo reported that Jupiter's satellites move faster the closer they are to
the planet: "the revolutions of the satellites which describe the smallest
circles round Jupiter are the most rapid" [G1610]. He gave no formula.

Kepler stated that the periodic times of any two planets are in the 3/2 power
of the ratio of their mean distances from the Sun [K1619]. The law is about
one central body and says nothing about what happens around another.

Newton reported the same rule separately for the satellites of Jupiter and of
Saturn. For the planets he wrote that their periodic times "are in the
sesquiplicate proportion of their mean distances from the sun. This
proportion, first observed by Kepler, is now received by all astronomers"
[N1687]. He then used periods and distances around different central bodies to
compare the quantities of matter in those bodies, which is where the mass of
the central body enters.

The question here is whether those claims can be recovered from data by
someone who does not know what the data are.

## 2. Hypotheses

- **H1**: `y = c · x1`. A naive baseline: proportional, and `x2` is ignored.
- **H2**: `y = c · x1^p`. Kepler's form if p = 3/2. `x2` is ignored.
- **H3**: `y = c · x1^p · x2^q`. A free power law in both variables.
- **H4**: `y = c · x1^(3/2) · x2^(−1/2)`. Newton's form, one free constant.

## 3. Methods

**Blind protocol.** `data/make_dataset.py` renames the central bodies to
groups A to G and the columns to `x1`, `x2`, `y`, rescales each column by an
arbitrary unit, and multiplies each value by log-normal noise
({100 * rv['noise']['x1_and_y']:.0f}% on `x1` and `y`; {100 * rv['noise']['x2_per_group']:.0f}% on `x2`, drawn once per group). The key
that undoes this is not used by anything in sections 4.1 to 4.3.

**Split.** {d['n_train']} rows in groups {', '.join(d['train_groups'])} were used for fitting and
{d['n_test']} rows in groups {', '.join(d['test_groups'])} were held out. No held-out group shares a
value of `x2` with a training group.

**Fitting and comparison.** Ordinary least squares on log10 values. Errors are
mean absolute residuals in dex (0.1 dex is about 26%). AIC and BIC use the
training residuals.

**Uncertainty.** {r['bootstrap']['resamples']} bootstrap resamples of all {d['n_rows']} rows, done two
ways: resampling rows, and resampling whole groups.

**Does `x2` matter?** A nested F-test of H2 against H3, and a group-level
check that fits one intercept per group and regresses the
{mt['group_level']['n_groups']} intercepts on log `x2`.

## 4. Results

### 4.1 Competing hypotheses

{chr(10).join(table)}

Both hypotheses that ignore `x2` miss the held-out groups by
{min(hyp['H1']['test_log_error'], hyp['H2']['test_log_error']):.2f} dex or more. Adding `x2` cuts the held-out error to
{hyp['H3']['test_log_error']:.3f} dex (H3) and {hyp['H4']['test_log_error']:.3f} dex (H4). H4 has the lowest BIC
({hyp['H4']['bic']:.1f} against {hyp['H3']['bic']:.1f} for H3): fixing the exponents at 3/2 and −1/2
costs almost no accuracy and saves two parameters.{evolved_text}

![Predicted against observed y for H2 and H3]({FIGURE})

### 4.2 Exponents

Fitted on all rows, H3 gives p = {ex['p']:.3f} and q = {ex['q']:.3f}.

| Resampling | 95% interval for p | 95% interval for q | 3/2 and −1/2 inside |
| --- | --- | --- | --- |
| rows | {interval(rows_iv['p'])} | {interval(rows_iv['q'])} | {yes_no(rows_iv['contains_3_2'] and rows_iv['contains_minus_1_2'], 'yes', 'no')} |
| groups | {interval(groups_iv['p'])} | {interval(groups_iv['q'])} | {yes_no(groups_iv['contains_3_2'] and groups_iv['contains_minus_1_2'], 'yes', 'no')} |

### 4.3 Significance of `x2`

The F-test rejects the null hypothesis that `x2` has no effect:
F({mt['f_test']['df'][0]}, {mt['f_test']['df'][1]}) = {mt['f_test']['f']:.0f}, p = {mt['f_test']['p_value']:.1e}. That test treats all rows as
independent, which they are not. The group-level check, with one point per
group, gives q = {mt['group_level']['q']:.3f} ± {mt['group_level']['q_stderr']:.3f} and p = {mt['group_level']['p_value']:.1e}.

### 4.4 Reveal

`x1` is the {rv['meaning']['x1']}, `x2` is the {rv['meaning']['x2']} and `y`
is the {rv['meaning']['y']}. Training groups: {train_names}. Held-out groups:
{test_names}. H4 is `{rv['law']}`, and its fitted constant implies

**G = {rv['g_estimate']:.3e} m³ kg⁻¹ s⁻²** (accepted {g_acc:.3e}; {100 * rv['g_relative_error']:+.1f}%).

| Resampling | 95% interval for G | Accepted value inside |
| --- | --- | --- |
| rows | {interval(g_rows, '.3e')} | {yes_no(in_rows, 'yes', 'no')} |
| groups | {interval(g_groups, '.3e')} | {yes_no(in_groups, 'yes', 'no')} |

## 5. Discussion

**Galileo.** {verdict(ex['p'] > 0)}. `y` rises with `x1`: the fitted exponent p is positive.

**Kepler.** {verdict(groups_iv['contains_3_2'])} for the exponent: the interval for p
{yes_no(groups_iv['contains_3_2'])} 3/2. But H2, his form taken literally as a statement about
all the data, misses the held-out groups by {hyp['H2']['test_log_error']:.3f} dex. A law in `x1` alone
cannot carry over from one central body to another.

**Newton.** {verdict(groups_iv['contains_minus_1_2'])}. The interval for q {yes_no(groups_iv['contains_minus_1_2'])} −1/2, and with
that exponent a single constant predicts the held-out central bodies to
{hyp['H4']['test_log_error']:.3f} dex.

**Two intervals for G.** The row interval {yes_no(in_rows)} the accepted value
and the group interval {yes_no(in_groups)} it. The group interval is the one to
trust. The largest error here is in `x2`, and it is shared by every row in a
group, so there are effectively {mt['group_level']['n_groups']} independent pieces of information about
the constant, not {d['n_rows']}. Resampling rows hides that and reports an interval
that is too narrow.

## 6. Limitations

- {mt['group_level']['n_groups']} central bodies is a small sample for any claim about `x2`.
- The noise was simulated and log-normal. Real historical errors were neither.
- The hypotheses were all power laws. Nothing here rules out other forms that
  agree with a power law over this range.
- H4's exponents were chosen after seeing H3's fit, so H4's good score is
  partly post hoc. A fresh set of systems would be the fair test.
- The masses in `data/orbits.csv` are modern values, themselves derived using
  this law. The estimate of G is a consistency check, not a measurement.

## 7. AI-use statement

Candidate hypotheses can come from Stage 1 (Open Coscientist or the Gemini
app) and Stage 2 (OpenEvolve). The statistics were computed by
`03_tests/hypothesis_tests.py` with no AI model involved. This text is a fixed
template filled by a script; no language model wrote it. A human is
responsible for every claim.

## References

- [G1610] Galileo Galilei. *Sidereus Nuncius*. Venice, 1610. Trans. E. S. Carlos, 1880.
- [K1619] Johannes Kepler. *Harmonices Mundi*, Book V, ch. 3. Linz, 1619.
- [N1687] Isaac Newton. *Principia*, Book III. London, 1687. Trans. A. Motte, 1729.
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--results", type=Path, default=ROOT / "results")
    parser.add_argument("--out", type=Path, default=ROOT / "paper" / "report.md")
    args = parser.parse_args()

    results_file = args.results / "results.json"
    if not results_file.exists():
        raise SystemExit(f"{results_file} not found. Run 03_tests/hypothesis_tests.py first.")
    with open(results_file) as f:
        results = json.load(f)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build(results))
    shutil.copyfile(args.results / FIGURE, args.out.parent / FIGURE)
    print(f"Wrote {args.out} and {args.out.parent / FIGURE}")


if __name__ == "__main__":
    main()
